# ===================================================
# meta infos
# ===================================================

meta:
  project: bb-buildingblock
  include:
  - dobi.yaml

# ===================================================
# alias
# ===================================================

alias=build:
  tasks:
  - bb-buildingblock-build
  annotations:
    description: "[alias] bb-buildingblock-build"
  
alias=deploy:
  tasks:
  - bb-buildingblock-deploy
  annotations:
    description: "[alias] bb-buildingblock-deploy"
  
alias=test: 
  tasks:
  - bb-buildingblock-test
  annotations: 
    description: "[alias] bb-buildingblock-test"