# ===================================================
# meta infos
# ===================================================

meta:
  project: bb-yocto-builder
  include:
  - dobi.yaml
  - version.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
  - bb-yocto-builder-version
  annotations:
    description: "[alias] bb-yocto-builder-version"

alias=build:
  tasks:
  - bb-yocto-builder-build-qemuarm-core-image-minimal
  annotations:
    description: "[alias] bb-yocto-builder-build-qemuarm-core-image-minimal"

alias=interactive:
  tasks:
  - bb-yocto-builder-interactive-build-shell
  annotations:
    description: "[alias] bb-yocto-builder-interactive-build-shell"

alias=test:
  tasks:
  - bb-yocto-builder-run-yocto-qemuarm-core-image-minimal-interactive
  annotations:
    description: "[alias] bb-yocto-builder-run-yocto-qemuarm-core-image-minimal-interactive"
